swagger: "2.0"
info:
  version: "v1"
  title: dmp Data Query APIs
  description: dmp Data Query APIs

basePath: /regions/{regionId}/dmp

paths:
  "/getPackageId":
    ###################### dmp APIs Query packageId in batch according to deviceId######################
        get:
              description: Query Crowd Package ID according to device ID
              operationId: getPackageId
              x-jdcloud-internal: false
              parameters:
                - name: deviceIds
                  in: query
                  required: true
                  type: string
                  description: "MD5 (deviceId), multiple MD5 (deviceId) separated by English commas. Note: MD5 result is in lowercase."
              responses:
                200:
                  description: OK
                  schema:
                    properties:
                      result:
                        properties:
                          status:
                            type: boolean
                            description: True is success, false is failure
                          message:
                            type: string
                            description: Description Information
                          data:
                            type: string
                            description: Map<String,String>>, the serialized character string needs to be reconverted before use. Key is deviceId, value is crowd package Id
                      requestId:
                        type: string
                        description: Request ID, requests are different at each time
                500:
                  description: "Internal server error"

# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: "Region ID"