swagger: "2.0"
info:
  version: "v1"
  title: User Management APIs
  description: "User Management APIs"

basePath: /regions/{regionId}

paths:
  "/subUser":
    ###################### Create Sub-accounts######################
    post:
      description: "Create sub-accounts"
      operationId: createSubuser
      x-jdcloud-internal: false
      parameters:
        - name: createSubUserInfo
          in: body
          description: "Sub-account Information"
          required: true
          schema:
            $ref: "../model/CreateSubUserInfo.yaml#/definitions/createSubUserInfo"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string

  "/userAccessKeys":
    ###################### Obtaining User’s All AccessKeys ######################
    get:
      description: "Search AccessKey list"
      operationId: describeUserAccessKeys
      x-jdcloud-internal: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  userAccessKeys:
                   type: array
                   description: "UserAccessKey list"
                   items:
                     $ref: "../model/UserAccessKey.yaml#/definitions/userAccessKey"
              requestId:
                type: string

  "/userAccessKey":
    ###################### Create AccessKey ######################
    post:
      description: "Create AccessKey"
      operationId: createUserAccessKey
      x-jdcloud-internal: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string


  "/userAccessKey/{accessKey}:enabled":
    ###################### Enable AccessKey ######################
    put:
      description: "Enable AccessKey"
      operationId: enabledUserAccessKey
      x-jdcloud-internal: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string


  "/userAccessKey/{accessKey}:disabled":
    ###################### Disable AccessKey ######################
    put:
      description: "Disable AccessKey"
      operationId: disabledUserAccessKey
      x-jdcloud-internal: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string

  "/userAccessKey/{accessKey}":
    ###################### Delete AccessKey ######################
    delete:
      description: "Delete AccessKey"
      operationId: deleteUserAccessKey
      x-jdcloud-internal: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              requestId:
                type: string


  "/user:describeUserInfo":
    ###################### Obtain User’s Information Based on AccessKey or AccountId ######################
    get:
      description: "Obtain user’s information based on AccessKey or AccountId"
      operationId: describeUserInfo
      x-jdcloud-internal: true
      parameters:
        - name: accessKey
          in: query
          type: string
          description: "User AccessKey"
          required: false
        - name: accountId
          in: query
          type: string
          description: "User’s Unique id"
          required: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  pin:
                    type: string
                    description: "User Pin, if there is a sub-account, its format is primary account pin @ sub-account pin"
                  enabled:
                    type: boolean
                    description: "If the user is available; true means that the user available, while false means that the user is unavailable and the user is in the blacklist"
                  authStatus:
                    type: integer
                    description: "0-Unverfied, 1-Verified (personal), 2-Verified (enterprise), 3-Verified (personal and enterprise)"
                  accountId:
                    type: integer
                    format: int64
                    description: "User’s Unique id"
                  accessKey:
                    type: string
                    description: "AccessKey, blank when inputting a parameter as accountId"
                  accessKeySecret:
                    type: string
                    description: "AccessKeySecret, blank when inputting parameter as accountId"
                  state:
                    type: integer
                    description: "AccessKey status, 0-Disabled, 1-Enabled, blank when inputting a parameter as accountId"
                  yn:
                    type: integer
                    description: "Deleted or not, 0-Deleted, 1-Valid, blank when inputting a parameter as accountId"
              requestId:
                type: string

  "/user:describeBaseInfo":
    ###################### Obtain user’s basic information based on user pin ######################
    get:
      description: "Obtain user’s basic information based on user pin"
      operationId: describeBaseInfo
      x-jdcloud-internal: true
      parameters:
        - name: pin
          in: query
          type: string
          description: "User Pin"
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  pin:
                    type: string
                    description: "User Pin"
                  enabled:
                    type: integer
                    description: "If the user is available; 1 means that the user available, while 0 means that the user is unavailable and the user is in the blacklist"
                  userType:
                    type: integer
                    description: "User Type 1: Person, 2: Enterprise, 3: Upgraded individual enterprise"
                  personAuthStatus:
                    type: integer
                    description: "-1-Unverified (personal), 1-Verified (personal)"
                  companyaAuthStatus:
                    type: integer
                    description: "0-Reviewing (Enterprise), 1-Verified (Enterprise), 2-Failed (Enterprise)"
                  accountBalance:
                    type: number
                    description: "Account Balance"
                  accountId:
                    type: integer
                    format: int64
                    description: "User’s Unique id"
                  meta:
                    type: string
                    description: "User’s Extended Information"
                  activeStatus:
                    type: integer
                    description: "User’s Activation Status"
                  cscPhone:
                    type: string
                    description: "User’s Mobile Phone Number"
                  cscEmail:
                    type: string
                    description: "User’s Email"
              requestId:
                type: string

  "/user:describeUserThreshold":
    ###################### Obtain user’s doorhead value based user pin ######################
    get:
      description: "Obtain user’s threshold value based user pin"
      operationId: describeUserThreshold
      x-jdcloud-internal: true
      parameters:
        - name: pin
          in: query
          type: string
          description: "User Pin"
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  pin:
                    type: string
                    description: "User Pin"
                  threshold:
                    type: number
                    description: "Threshold Value"
              requestId:
                type: string

  "/describeGlobalAzSaleStatus":
      ###################### Obtain availability zone status under all regions ######################
      get:
        description: "Obtain availability zone status under all regions"
        operationId: describeGlobalAzSaleStatus
        x-jdcloud-internal: true
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                result:
                  properties:
                    data:
                      type: array
                      items:
                        $ref: "../model/BaseProductRegionVo.yaml#/definitions/baseProductRegionVo"
                requestId:
                  type: string


  "/describeGlobalAzMapping":
      ###################### Obtain availability zone mapping relations under all regions ######################
      get:
        description: "Obtain availability zone mapping relations under all regions"
        operationId: describeGlobalAzMapping
        x-jdcloud-internal: true
        parameters:
         - name: pin
           in: query
           type: string
           description: "User Pin"
           required: true
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                result:
                  properties:
                    data:
                      type: array
                      items:
                        $ref: "../model/GlobalAzMappingVo.yaml#/definitions/globalAzMappingVo"
                requestId:
                  type: string


# Path General Parameters
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  accessKey:
    name: accessKey
    in: path
    required: true
    type: string
    description: accessKey